#!/usr/bin/env python3
"""Build the interactive 3D view of the lab from a snapshot.json.

    python3 build.py [snapshot.json] [--out DIR] [--artifact]

Writes index.html: one self-contained page (three.js, fonts and the snapshot are embedded; it needs no
network and can be opened from disk or served by GitHub Pages). With --artifact it also writes
artifact.html, the same page as a fragment for claude.ai, which loads three.js from cdnjs instead.

Default snapshot: ../snapshots/03-final/snapshot.json (i.e. docs/lab/snapshots/03-final/ when this
folder is docs/lab/visuals/). Needs Python 3 only.
"""

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent
SRC = ROOT / "src"
THREE_CDN = "https://cdnjs.cloudflare.com/ajax/libs/three.js/r128/three.min.js"

args = sys.argv[1:]
want_artifact = "--artifact" in args
out_dir = pathlib.Path(args[args.index("--out") + 1]) if "--out" in args else ROOT
positional = [
    a
    for i, a in enumerate(args)
    if not a.startswith("--") and (i == 0 or args[i - 1] != "--out")
]
snapshot_path = (
    pathlib.Path(positional[0])
    if positional
    else ROOT.parent / "snapshots" / "03-final" / "snapshot.json"
)
if not snapshot_path.exists():
    sys.exit(
        f"snapshot not found: {snapshot_path}\nusage: python3 build.py path/to/snapshot.json [--out DIR]"
    )
snapshot = json.loads(snapshot_path.read_text())

fonts = json.loads((ROOT / "vendor" / "fonts.json").read_text())
font_css = "\n".join(
    # Percent formatting on purpose: the text is CSS, whose braces would all need doubling in an f-string.
    '@font-face{font-family:"%s";font-style:normal;font-weight:%d;font-display:block;'  # noqa: UP031
    'src:url(data:font/woff;base64,%s) format("woff")}'
    % (f["family"], f["weight"], f["b64"])
    for f in fonts
)

css = (SRC / "style.css").read_text()
body = (SRC / "body.html").read_text()
app = "\n".join(p.read_text() for p in sorted((SRC / "app").glob("*.js")))
app = "(function () {\n'use strict';\n" + app + "\n})();"
three = (ROOT / "vendor" / "three.r128.min.js").read_text()

# "</" must not appear inside an inline <script>
snap_json = json.dumps(snapshot, separators=(",", ":")).replace("</", "<\\/")
title = "HTCondor Batch Farm 3D"
desc = (
    "Interactive 3D view of the HTCondor batch farm lab: three AlmaLinux machines on AWS, "
    "built by OpenTofu, bootstrapped by Ansible, configured by OpenVox."
)

NOTICE = (
    "<!-- Generated by build.py from snapshot.json (milestone {}). Do not edit by hand.\n"
    "     Embedded: IBM Plex Sans, Sans Condensed and Mono (Latin subsets), (c) IBM Corp., SIL Open Font License 1.1;\n"
    "     three.js r128, (c) three.js authors, MIT License. -->\n".format(
        snapshot.get("milestone", "?")
    )
)

head = f"<title>{title}</title>\n{NOTICE}<style>\n{font_css}\n{css}\n</style>\n"
content = (
    f'{body}\n<script type="application/json" id="snapshot">{snap_json}</script>\n'
)

# claude.ai wraps the fragment in its own document, so title and style simply come first
artifact = (
    head
    + content
    + f'<script src="{THREE_CDN}"></script>\n<script>\n{app}\n</script>\n'
)

RESET = (
    "html{color-scheme:light}body{margin:0;font:14px/1.45 system-ui,sans-serif}"
    "img{max-width:100%}[hidden]{display:none!important}"
)
standalone = (
    '<!doctype html>\n<html lang="en">\n<head>\n<meta charset="utf-8">\n'
    '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">\n'
    f'<meta name="description" content="{desc}">\n'
    f'<meta property="og:title" content="HTCondor Batch Farm as Code">\n'
    f'<meta property="og:description" content="{desc}">\n'
    '<meta property="og:type" content="website">\n'
    # Published by GitHub Pages from the main branch; link previews (LinkedIn, Slack) use this image.
    '<meta property="og:url" content="https://vinsl.github.io/HTCondor-Batch-Farm/docs/lab/visuals/">\n'
    '<meta property="og:image" content="https://vinsl.github.io/HTCondor-Batch-Farm/docs/lab/visuals/linkedin-light.png">\n'
    '<meta property="og:image:width" content="2400">\n'
    '<meta property="og:image:height" content="1256">\n'
    '<meta name="twitter:card" content="summary_large_image">\n'
    f"<style>{RESET}</style>\n{head}</head>\n<body>\n"
    + content
    + f"<script>\n{three}\n</script>\n<script>\n{app}\n</script>\n</body>\n</html>\n"
)

out_dir.mkdir(parents=True, exist_ok=True)
(out_dir / "index.html").write_text(standalone)
print(
    f"index.html: {(out_dir / 'index.html').stat().st_size / 1024:.0f} KB  (snapshot {snapshot.get('milestone', '?')})"
)
if want_artifact:
    (out_dir / "artifact.html").write_text(artifact)
    # local preview of the fragment, wrapped the way the publisher wraps it
    (out_dir / "artifact-preview.html").write_text(
        '<!doctype html><html><head><meta charset=utf8><meta name=viewport content="width=device-width,'
        f'initial-scale=1,viewport-fit=cover"><style>{RESET}</style></head><body>{artifact}</body></html>'
    )
    print(f"artifact.html: {(out_dir / 'artifact.html').stat().st_size / 1024:.0f} KB")
